# Trial Period
### Round 1

1. Enter edit mode
2. Press `Shift + Enter` to run the current cell and create a new cell

### Round 2

1. Enter edit mode
2. Press `Control + Enter` to **ONLY** run the current cell



In [1]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]],
               [[7, 8, 9], [10, 11, 12]]])

print(arr)
print(type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>


In [ ]:
print(arr.ndim) # prints the number of dimensions

3
